name = "ray_tracing"
uuid = "70ba8d3e-7e9c-4fa8-ad1b-bc738f0ffbc7"
authors = ["Edward Stables <edward.stables1198@gmail.com>"]
version = "0.1.0"

[deps]
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
